### ISSUE TITLE
Local response #ref not rendering

### ISSUE THREAD

**Issue by yao-charlie** [42Crunch/vscode-openapi#138]
So... as still a programming novice, forgive me if I'm making any errors in submitting an issue, etc. I searched but didn't find this exact thing either...

Given:
```
responses:
        200:
          description: Return something
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/foo'
```

with the $ref:
```
components:
  # not sure how some of the formats are defined...
  schemas:
    foo:
      type: object
      required:
        - property1
      properties:
        property1:
          type: string
          format: UUID
        property2: 
          type: string

```

results in: 

😱 Could not render n, see the console.

However, it renders perfectly fine in the official swagger editor, as far as I can tell. Since other schemas work, I'm assuming it breaks somewhere with that $ref.

Thanks - love the plug-in!
