### ISSUE TITLE
Problems with nullable types.

### ISSUE THREAD

**Issue by DigiLive** [42Crunch/vscode-openapi#192]
Having an OpenAPI 3.0.3 specification in yaml, below code will result in reporting 'Example is not consistent with the underlying schema' by the auditor.

```yaml
application/json:
  schema:
    type: object
    properties:
      reply:
        type: integer
        nullable: true
    additionalProperties: false
  example:
    reply: null
```
Note: This is only a part of a response component.

In my use case the value of reply will always be `null`, hence above example.
IMHO, once a type is defined as nullable, example value `null` should be accepted (or how else would I set it as an accepted example value?).

In addition, setting the type of property 'reply' to `object`, the auditor reports 'Schema of a JSON object in a response has no properties defined'.
IMHO, once an object is defined as nullable, having properties isn't a requirement anymore.
