### ISSUE TITLE
Unable to resolve reference if used more than once

### ISSUE THREAD

**Issue by carlosli888** [42Crunch/vscode-openapi#221]
##### Description
I am encountering errors in the *OpenAPI SwaggerUI preview* if any schema references another schema more than once.  What I mean is if I have more than one property that references the same schema file, I get a **`Resolver error`** because it is unable to resolve the reference.

##### version
4.16.6

##### OpenAPI file(s)

```yaml
# openapi.yaml
openapi: 3.0.2  
info:
  title: API Test
  version: 0.1.0
servers: 
  - url: 'https://localhost:3000/api/v1'

paths:
  /test:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./product-line.yaml
```

```yaml
# product-line.yaml
title: Product Line
type: object
properties:
  gen1:
    $ref: ./widget.yaml
  gen2:
    $ref: ./widget.yaml
```

```yaml
# widget.yaml
title: Widget
type: object
properties:
  id: 
    type: string
    format: uuid
  name: 
    type: string
required:
  - id
  - name
```

##### Steps to reproduce

1.  Create the 3 `yaml` files containing the content above.
2.  Open VSCode with the [*OpenAPI (Swagger) Editor*](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi) installed (v4.16.6).
3.  Open the folder containing the 3 files from step 1.
4.  Select the `openapi.yaml` file.
5.  Open the *API Preview* (e.g., `Shift`+`Alt`+`P`).
6.  Notice that no errors are shown.
7.  Expand the `Product Line` schema.
8.  Notice that the top of the preview has `Resolver error`.
9.  Attempt to expand the second property (i.e., `gen2`).
10. Notice that it is unable to render the referenced schema even if it is the same one as the first (`gen1`) property.

##### Additional Info
If only one of `gen1` or `gen2` properties are defined, then it works fine.  The example and reproduction shown is a simplified example.  This issue was initially discovered with a more complicated setup that also made use of `oneOf`.  This means that the reference does not have to appear in the same file.  It can appear anywhere in the tree.  For example:
* We want to look at the *schema* for a `geometry`.
* The `geometry` type is described in a `geometry.yaml` file and uses `oneOf` to indicate that it can be either a `point`, `line`, or `polygon`.  Each of those types of shapes are defined in their own respective files.
* Each shape is defined using `position` to represent the vertices.  The `position` is defined in its own file.
* Because the `position` type is indirectly referenced multiple times, the same *resolver error* is encountered.
