### ISSUE TITLE
Version 3.1 doesn't supported

### ISSUE THREAD

**Issue by razb-viola** [42Crunch/vscode-openapi#258]
When trying to run my OAS file, which is on v3.1 and trying to open a route in the viewer, the whole screen gets red with like 1k rows of impossible to understand error.

Then I change the version to 3.0.0 and it works - however, I get in the VSCode the following lines with red underline:

```
components:
  securitySchemes:
    header:
      type: http
      scheme: bearer
      name: accesstoken
      in: header
      bearerFormat: JWT
    cookie:
      type: apiKey
      scheme: bearer
      name: accesstoken
      in: cookie
      bearerFormat: JWT
      description: Do not forget to add Bearer and space before the token value
```
