### ISSUE TITLE
Can't $ref from a specific HTTP method

### ISSUE THREAD

**Issue by dannflor** [42Crunch/vscode-openapi#268]
Something like
```
paths:
  /poll:
    $ref: "./poll.yaml#/paths/poll"
```
parses without error but
```
paths:
  /poll:
    get:
      $ref: "./poll.yaml#/paths/poll/get"
```
gives the errors: `Property $ref not allowed` and `Missing property "responses"`  despite being valid OpenAPI syntax
