### ISSUE TITLE
Support for external HTTP references behind proxy

### ISSUE THREAD

**Issue by camball** [42Crunch/vscode-openapi#271]
I'm not expert on proxies, but I'm having trouble getting validation to work when pulling in [externally-defined HTTP references](https://github.com/42Crunch/vscode-openapi/blob/master/WHATS-NEW.md#support-for-external-http-references). I get an error like:

```txt
Error reading file "https://github.mycompany.com/.../component.yaml: cannot open openapi-internal-https://github.mycompany.com/.../component.yaml. Detail: Response code 401 (Unauthorized)"
```

I added `github.mycompany.com` to my `openapi.approvedHostnames`:

```txt
"openapi.approvedHostnames": [
    "github.mycompany.com"
]
```

and the 401 is where I'm stuck with. I'm wondering if it's a proxy issue, or otherwise, and if there's a solution at all here. Thanks!

**Comment by ak1394** [comment]
Hi @camball !

We've recently added some support for authentication for external references, the details in the README file in "Configure authentication for external references in OpenAPI files" section.

Do you know the necessary authentication details required to retrieve files from "https://github.mycompany.com/" ?

**Comment by camball** [comment]
Thanks—that worked great! Didn't realise that settings pane existed, lol.

Now that I have that working, I now get another error which I believe is unrelated, `Failed to resolve $ref`. I didn't mention before, but the full URL structure I am pulling in looks like:

```yaml
// does not work

parameters:
- $ref: 'https://github.mycompany.com/api/v3/repos/.../parameters.yaml#/MyParameter'
```

where it uses JSON Pointer notation to reference just the key `MyParameter`. When I take away the pointer notation, the error goes away and the reference is resolved just fine:

```yaml
// works

parameters:
- $ref: 'https://github.mycompany.com/api/v3/repos/.../parameters.yaml'
```

This I think may be an issue with the extension, but am not sure. I know the extension supports JSON Pointers, but am wondering if there is an issue with it being as part of an external URL.

**Comment by ak1394** [comment]
Could you provide a snippet from, or a whole `parameters.yaml`?

**Comment by camball** [comment]
Sure, here's the full content of `parameters.yaml`, with some replaced values:

```yaml
Authorization:
  name: Authorization
  in: header
  required: true
  description: My Authorization description
  schema:
    type: string
    example: an example here
an-id:
  name: an-id
  in: header
  description: My ID description
  required: true
  schema:
    type: string
```
