### ISSUE TITLE
Wrong warning for pattern rule

### ISSUE THREAD

**Issue by ansidev** [42Crunch/vscode-openapi#29]
I have a model:

```
User:
      type: object
      properties:
        firstName:
          type: string
          maxLength: 100
          pattern: /^[\w\s]+$/
          example: John
        lastName:
          type: string
          maxLength: 100
          pattern: /^[\w\s]+$/
          example: Doe
        fullName:
          type: string
          maxLength: 100
          pattern: /^[\w\s]+$/
          example: John Doe
```

The warnings are `The value of the schema example '/components/schemas/User/properties/{firstName, lastName, fullName}/example' is not consistent with the schema`.
