### ISSUE TITLE
Unable to display Example Value of prefixItems

### ISSUE THREAD

**Issue by lynn-beckman** [42Crunch/vscode-openapi#333]
When prefixItems is used in an array definition, the Example Value of the API in the preview page is displayed as null.
```YAML
type: object
properties:
  items:
    type: array
    description: The actions of the task.
    prefixItems:
      - $ref: './A.yaml'
      - oneOf:
        - $ref: './B.yaml'
        - $ref: './C.yaml'
      - $ref: './D.yaml'
    minItems: 3
    maxItems: 3
```
