### ISSUE TITLE
"JS-YAML: expected a single document in the stream, but found more" on non-OpenAPI YAML files

### ISSUE THREAD

**Issue by TBBle** [42Crunch/vscode-openapi#45]
With a random YAML file (happens to contain some kubernetes resource definitions) this extension causes a problem report
> JS-YAML: expected a single document in the stream, but found more

Repro case: file named _ed-ks1-test.yaml_.
```
---
apiVersion: agones.dev/v1
kind: Fleet
spec:
  replicas: 1
  scheduling: Distributed
  template:
    spec:
      ports:
        - name: default
          containerPort: 7777
      template:
        spec:
          containers:
            - resources:
                limits:
                  cpu: "1"
                  memory: "1Gi"
---
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
spec:
  fleetName: demo-arena-v1
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 0
      maxReplicas: 10
```

The error is triggered on the second `---` instance.

I've confirmed that disabling only this extension causes the problem report to go away.

This is using 42crunch.vscode-openapi version 2.1.1, and redhat.vscode-yaml 0.7.2.

I'm not sure if the problem is the use of `load` instead of `loadAll` from `yaml-ast-parser-custom-tags` and `js-yaml`, or if the problem is that this error report is not being suppressed correctly when the file is identified as "not an OpenAPI definition" after loading.
