### ISSUE TITLE
Audit fails with $ref that points to another file and contains ~1

### ISSUE THREAD

**Issue by stevenj** [42Crunch/vscode-openapi#54]
I am getting the error 
```text
Unexpected error when trying to audit API: Error: Unable to locate node: #/paths/~1auth~1newcustomer/post/url
```
Trying to audit my file.

The path element in question is:

```yaml
paths:
  /v1/auth/newcustomer: # Causes a new customer email to be sent
    $ref: "v1/auth/newcustomer.yml#/paths/~1auth~1newcustomer"
```

Which is a valid reference.
