### ISSUE TITLE
Counting character in example is not working

### ISSUE THREAD

**Issue by mbarnach** [42Crunch/vscode-openapi#70]
Considere the following component:

```YAML
AnonymizedField:
  description: An anonymized field where value and length are irrelevant.
  type: string
  minLength: 10
  maxLength: 10
  pattern: '••••••••••'
  example: ••••••••••
```
The audit returns the error that the example is not consistent with the schema.
If the maxLength is set to 30, then the example is fine.
The character is the "standard" bullet character, but I get the same issue with non-ascii character (I've tried the Emoji also).
